const { connectDB, getDB, client } = require('./config/db');
require('dotenv').config();

const seedData = {
  players: [
    { id: 'p1', number: 1, name: 'Sipho Dlamini', position: 'Goalkeeper', dob: '1998-03-14', nationality: 'South African', height: '1.88m', preferredFoot: 'Right', biography: 'Sipho is the commanding presence between the sticks for Mphehli All Stars. Known for his commanding crosses and sharp reflexes, he has been a rock for the defence since joining the club. A natural leader who organises the backline with authority.', appearances: 24, goals: 0, assists: 1, cleanSheets: 9, status: 'active', featured: true },
    { id: 'p2', number: 2, name: 'Thabo Nkosi', position: 'Defender', dob: '2000-07-22', nationality: 'South African', height: '1.81m', preferredFoot: 'Right', biography: 'A tenacious right-back who combines defensive solidity with an ability to bomb forward and deliver quality crosses. Thabo has been one of the club\'s most consistent performers since the founding year.', appearances: 21, goals: 2, assists: 4, cleanSheets: 0, status: 'active', featured: false },
    { id: 'p3', number: 5, name: 'Lethabo Mokoena', position: 'Defender', dob: '1997-11-08', nationality: 'South African', height: '1.85m', preferredFoot: 'Left', biography: 'The heart of the Mphehli All Stars defence, Lethabo reads the game exceptionally well and his composure on the ball makes him equally comfortable playing out from the back. A true defender\'s defender.', appearances: 23, goals: 3, assists: 1, cleanSheets: 0, status: 'active', featured: true },
    { id: 'p4', number: 6, name: 'Bongani Zulu', position: 'Defender', dob: '1999-04-17', nationality: 'South African', height: '1.83m', preferredFoot: 'Right', biography: 'Strong in the air and dominant in the challenge, Bongani is the kind of centre-back who opposition strikers dread facing. His leadership qualities are evident both on and off the pitch.', appearances: 18, goals: 1, assists: 0, cleanSheets: 0, status: 'active', featured: false },
    { id: 'p5', number: 3, name: 'Mpho Sithole', position: 'Defender', dob: '2001-09-30', nationality: 'South African', height: '1.78m', preferredFoot: 'Left', biography: 'An attack-minded left-back who loves to get forward and contribute to the team\'s attacking play. Mpho\'s pace and technique make him a constant threat going forward.', appearances: 20, goals: 1, assists: 6, cleanSheets: 0, status: 'active', featured: false },
    { id: 'p6', number: 8, name: 'Mandla Khumalo', position: 'Midfielder', dob: '1999-01-25', nationality: 'South African', height: '1.76m', preferredFoot: 'Right', biography: 'The engine room of Mphehli All Stars\' midfield, Mandla covers every blade of grass and wins crucial duels throughout the game. His work ethic and discipline set the tone for the entire team.', appearances: 24, goals: 5, assists: 8, cleanSheets: 0, status: 'active', featured: true },
    { id: 'p7', number: 4, name: 'Nhlanhla Ntuli', position: 'Midfielder', dob: '2000-06-12', nationality: 'South African', height: '1.74m', preferredFoot: 'Both', biography: 'A creative playmaker who operates in the centre of the park, Nhlanhla has the vision to unlock defences with incisive passes and the technical ability to influence games in tight spaces.', appearances: 22, goals: 7, assists: 11, cleanSheets: 0, status: 'active', featured: true },
    { id: 'p8', number: 7, name: 'Siyabonga Mthembu', position: 'Midfielder', dob: '1998-08-19', nationality: 'South African', height: '1.72m', preferredFoot: 'Right', biography: 'A wide midfielder with electric pace and a lethal final ball, Siyabonga is the kind of player who can change a game in an instant. His dribbling and crossing ability are among the best in the club.', appearances: 19, goals: 4, assists: 9, cleanSheets: 0, status: 'active', featured: false },
    { id: 'p9', number: 10, name: 'Lungelo Maphanga', position: 'Midfielder', dob: '2001-12-03', nationality: 'South African', height: '1.75m', preferredFoot: 'Left', biography: 'The number 10. The heartbeat. Lungelo is the most technically gifted player in the squad — his ability to turn tight situations into goalscoring opportunities makes him the player every fan wants to watch. The embodiment of "Cometh the hour, Cometh the man."', appearances: 23, goals: 13, assists: 14, cleanSheets: 0, status: 'active', featured: true },
    { id: 'p10', number: 11, name: 'Thulani Dube', position: 'Forward', dob: '2000-02-28', nationality: 'South African', height: '1.79m', preferredFoot: 'Left', biography: 'Raw pace, clinical finishing, and an insatiable hunger for goals define Thulani\'s game. A constant menace in behind opposition defences, he has developed into one of the most feared attackers in the league.', appearances: 22, goals: 16, assists: 5, cleanSheets: 0, status: 'active', featured: true },
    { id: 'p11', number: 9, name: 'Sibusiso Ndlovu', position: 'Forward', dob: '1997-05-16', nationality: 'South African', height: '1.82m', preferredFoot: 'Right', biography: 'A powerful centre-forward who leads the line with authority. Sibusiso is exceptional in the air, strong with his back to goal, and possesses a natural eye for goal that makes him one of the most complete strikers in the region.', appearances: 21, goals: 18, assists: 7, cleanSheets: 0, status: 'active', featured: true },
    { id: 'p12', number: 14, name: 'Ayanda Cele', position: 'Forward', dob: '2002-10-07', nationality: 'South African', height: '1.71m', preferredFoot: 'Right', biography: 'Young, hungry and supremely talented, Ayanda is the future of Mphehli All Stars. His directness, quick feet, and eye for a spectacular goal have already made him a fan favourite despite his age.', appearances: 17, goals: 9, assists: 3, cleanSheets: 0, status: 'active', featured: false },
  ],
  fixtures: [
    { id: 'f1', homeTeam: 'Mphehli All Stars', awayTeam: 'Riverside United', date: '2025-08-24', kickOff: '15:00', competition: 'Regional League', venue: 'Trezona Park, Florida', status: 'upcoming', preview: 'Mphehli All Stars host Riverside United in what promises to be an exciting Regional League encounter. Both sides enter the match in strong form and the home crowd will be vital.', published: true },
    { id: 'f2', homeTeam: 'Eastside FC', awayTeam: 'Mphehli All Stars', date: '2025-09-07', kickOff: '14:00', competition: 'Regional League', venue: 'Eastside Stadium', status: 'upcoming', preview: 'A tricky away day at Eastside FC. The All Stars will be looking to continue their impressive away form.', published: true },
    { id: 'f3', homeTeam: 'Mphehli All Stars', awayTeam: 'Valley Athletic', date: '2025-09-21', kickOff: '15:00', competition: 'Regional Cup', venue: 'Trezona Park, Florida', status: 'upcoming', preview: 'A Regional Cup tie against Valley Athletic. The All Stars are targeting a deep cup run this season.', published: true },
    { id: 'f4', homeTeam: 'Mphehli All Stars', awayTeam: 'Northern Stars', date: '2025-08-10', kickOff: '15:00', competition: 'Regional League', venue: 'Trezona Park, Florida', status: 'completed', homeScore: 3, awayScore: 1, report: 'Mphehli All Stars delivered a commanding home performance to defeat Northern Stars 3-1. Sibusiso Ndlovu opened the scoring with a powerful header before Thulani Dube doubled the lead with a clinical finish. Northern Stars pulled one back, but Lungelo Maphanga sealed the win with a superb long-range effort in the final ten minutes.', goalScorers: [{ player: 'Sibusiso Ndlovu', minute: 18, team: 'home' }, { player: 'Thulani Dube', minute: 34, team: 'home' }, { player: 'K. Moyo', minute: 67, team: 'away' }, { player: 'Lungelo Maphanga', minute: 81, team: 'home' }], cards: [{ player: 'B. Khumalo', type: 'yellow', minute: 45, team: 'away' }], lineupHome: ['Sipho Dlamini', 'Thabo Nkosi', 'Lethabo Mokoena', 'Bongani Zulu', 'Mpho Sithole', 'Mandla Khumalo', 'Nhlanhla Ntuli', 'Siyabonga Mthembu', 'Lungelo Maphanga', 'Thulani Dube', 'Sibusiso Ndlovu'], lineupAway: ['T. Dube', 'R. Sithole', 'K. Moyo', 'L. Nxumalo', 'B. Khumalo', 'M. Cele', 'A. Dlamini', 'S. Mthembu', 'T. Ndlovu', 'P. Zulu', 'N. Nkosi'], published: true },
    { id: 'f5', homeTeam: 'Highveld Rovers', awayTeam: 'Mphehli All Stars', date: '2025-07-27', kickOff: '14:30', competition: 'Regional League', venue: 'Highveld Park', status: 'completed', homeScore: 1, awayScore: 1, report: 'A hard-fought point for the All Stars at Highveld Rovers. Nhlanhla Ntuli cancelled out the home side\'s opener with a superb free-kick to secure a share of the spoils.', goalScorers: [{ player: 'T. Mokoena', minute: 23, team: 'home' }, { player: 'Nhlanhla Ntuli', minute: 58, team: 'away' }], cards: [], lineupHome: ['G. Khumalo', 'T. Sithole', 'T. Mokoena', 'D. Zulu', 'R. Nkosi', 'L. Maphanga', 'B. Dube', 'A. Cele', 'S. Ndlovu', 'M. Khumalo', 'P. Ntuli'], lineupAway: ['Sipho Dlamini', 'Thabo Nkosi', 'Lethabo Mokoena', 'Bongani Zulu', 'Mpho Sithole', 'Mandla Khumalo', 'Nhlanhla Ntuli', 'Siyabonga Mthembu', 'Lungelo Maphanga', 'Thulani Dube', 'Sibusiso Ndlovu'], published: true },
    { id: 'f6', homeTeam: 'Mphehli All Stars', awayTeam: 'Sunrise FC', date: '2025-07-13', kickOff: '15:00', competition: 'Regional League', venue: 'Trezona Park, Florida', status: 'completed', homeScore: 4, awayScore: 0, report: 'A dominant display at Mphehli Sports Ground as the All Stars crushed Sunrise FC 4-0. Sibusiso Ndlovu grabbed a brace, with Thulani Dube and Ayanda Cele completing the rout in front of a delighted home crowd.', goalScorers: [{ player: 'Sibusiso Ndlovu', minute: 12, team: 'home' }, { player: 'Thulani Dube', minute: 29, team: 'home' }, { player: 'Sibusiso Ndlovu', minute: 61, team: 'home' }, { player: 'Ayanda Cele', minute: 88, team: 'home' }], cards: [{ player: 'M. Sithole', type: 'red', minute: 71, team: 'away' }], published: true },
  ],
  news: [
    { id: 'n1', title: 'Mphehli All Stars Announce Exciting New Season Ambitions', category: 'Club News', author: 'Club Media', date: '2025-08-12', excerpt: 'The club sets its sights on a historic season as preparations reach full speed ahead of the Regional League campaign.', content: '...', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&h=600&fit=crop&auto=format', tags: ['Season Preview', 'Club News', 'Squad'], status: 'published', featured: true },
    { id: 'n2', title: 'Match Report: All Stars Dominate Northern Stars 3-1', category: 'Match Reports', author: 'Match Desk', date: '2025-08-10', excerpt: 'Three brilliant goals saw Mphehli All Stars claim all three points at home in a commanding Regional League display.', content: '...', image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=1200&h=600&fit=crop&auto=format', tags: ['Match Report', 'Regional League', 'Win'], status: 'published', featured: false },
    { id: 'n3', title: 'Lungelo Maphanga: "This Club Means Everything To Me"', category: 'Player News', author: 'Club Media', date: '2025-08-07', excerpt: 'Our number 10 opens up about his journey, his passion for Mphehli All Stars, and his goals for the season ahead.', content: '...', image: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=1200&h=600&fit=crop&auto=format', tags: ['Player Interview', 'Lungelo Maphanga'], status: 'published', featured: false },
    { id: 'n4', title: 'Youth Development Programme Launched', category: 'Community', author: 'Club Media', date: '2025-07-30', excerpt: 'Mphehli All Stars launches a grassroots youth development programme to nurture the next generation of local talent.', content: '...', image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=1200&h=600&fit=crop&auto=format', tags: ['Community', 'Youth', 'Development'], status: 'published', featured: false },
    { id: 'n5', title: 'Welcome: New Sponsors Announced Ahead of New Season', category: 'Announcements', author: 'Club Media', date: '2025-07-20', excerpt: 'Mphehli All Stars is delighted to welcome new commercial partners who share our vision and ambition.', content: '...', image: 'https://images.unsplash.com/photo-1574629181260-bc5e7d23e6d4?w=1200&h=600&fit=crop&auto=format', tags: ['Sponsors', 'Announcement', 'Partnerships'], status: 'published', featured: false },
    { id: 'n6', title: 'Looking Back: Three Years of Mphehli All Stars', category: 'Club News', author: 'Club Media', date: '2025-07-05', excerpt: 'As we enter our third year, we reflect on the incredible journey that has brought Mphehli All Stars to where we stand today.', content: '...', image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1200&h=600&fit=crop&auto=format', tags: ['History', 'Club Story', 'Three Years'], status: 'published', featured: false },
  ],
  gallery: [
    { id: 'g1', type: 'image', title: 'Match Day Action vs Northern Stars', description: 'Action shots from our 3-1 victory over Northern Stars', category: 'Matchday', url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-08-10', published: true },
    { id: 'g2', type: 'image', title: 'Pre-Season Training', description: 'The squad prepares hard ahead of the new season', category: 'Training', url: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-08-01', published: true },
    { id: 'g3', type: 'image', title: 'Stadium Atmosphere', description: 'The incredible atmosphere at Mphehli Sports Ground', category: 'Matchday', url: 'https://images.unsplash.com/photo-1574629181260-bc5e7d23e6d4?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1574629181260-bc5e7d23e6d4?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-07-28', published: true },
    { id: 'g4', type: 'image', title: 'Night Match Under the Lights', description: 'A memorable evening fixture at home', category: 'Matchday', url: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-07-20', published: true },
    { id: 'g5', type: 'image', title: 'Squad Photo 2025', description: 'Official Mphehli All Stars squad photo for the 2025 season', category: 'Players', url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-07-10', published: true },
    { id: 'g6', type: 'image', title: 'Supporters Celebrating', description: 'Our incredible supporters celebrate after the 4-0 win over Sunrise FC', category: 'Supporters', url: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-07-14', published: true },
    { id: 'g7', type: 'video', title: 'Goal of the Season Contender', description: 'Lungelo Maphanga\'s stunning long-range effort against Northern Stars', category: 'Matchday', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', thumbnail: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-08-11', published: true },
    { id: 'g8', type: 'image', title: 'Community Open Day', description: 'The club opens its doors to the local community', category: 'Events', url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=1200&h=800&fit=crop&auto=format', thumbnail: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&h=400&fit=crop&auto=format', uploadDate: '2025-06-28', published: true },
  ],
  sponsors: [
    { id: 's1', name: 'Mphehli Building Supplies', description: 'Our principal partner and the foundation on which the club is built. Mphehli Building Supplies has been with us since day one.', website: '#', tier: 'Main Partner', startDate: '2022-01-01', endDate: '2026-12-31', active: true, displayOrder: 1 },
    { id: 's2', name: 'All Stars Sportswear', description: 'Kit and sportswear partner providing our players with premium equipment to perform at their best.', website: '#', tier: 'Main Partner', startDate: '2023-01-01', endDate: '2026-06-30', active: true, displayOrder: 2 },
    { id: 's3', name: 'Riverside Medical Centre', description: 'Our official medical partners, keeping the squad fit and healthy throughout the season.', website: '#', tier: 'Official Partner', startDate: '2023-06-01', endDate: '2025-12-31', active: true, displayOrder: 3 },
    { id: 's4', name: 'Khumalo Legal Services', description: 'Providing legal support and guidance to the club and its stakeholders.', website: '#', tier: 'Official Partner', startDate: '2024-01-01', endDate: '2025-12-31', active: true, displayOrder: 4 },
    { id: 's5', name: 'Sunrise Food & Beverage', description: 'Official catering partners for matchday hospitality at Mphehli Sports Ground.', website: '#', tier: 'Official Partner', startDate: '2024-03-01', endDate: '2025-12-31', active: true, displayOrder: 5 },
    { id: 's6', name: 'Valley Transport Group', description: 'Keeping the All Stars moving — official transport partner for all away fixtures.', website: '#', tier: 'Community Partner', startDate: '2024-06-01', endDate: '2025-12-31', active: true, displayOrder: 6 },
  ],
  staff: [
    { id: 'st1', name: 'Coach Themba Mabaso', role: 'Head Coach', biography: 'Themba Mabaso founded Mphehli All Stars in 2022 with a vision to build a football club that reflects the values of the community. A former professional footballer with decades of coaching experience, he brings tactical sophistication and inspirational leadership to the dugout.', displayOrder: 1, status: 'active' },
    { id: 'st2', name: 'Nkosi Phiri', role: 'Assistant Coach', biography: 'Nkosi works closely with the head coach to prepare the squad tactically and technically. His attention to detail and ability to work with individual players on their development has been invaluable.', displayOrder: 2, status: 'active' },
    { id: 'st3', name: 'Zanele Dlamini', role: 'Team Manager', biography: 'Zanele is the organisational backbone of the club, managing logistics, administration, and the day-to-day operations that keep Mphehli All Stars running smoothly.', displayOrder: 3, status: 'active' },
    { id: 'st4', name: 'Dr. Lindiwe Khumalo', role: 'Club Doctor', biography: 'Dr. Khumalo oversees the medical welfare of all players, managing injuries, rehabilitation, and player fitness with the highest professional standards.', displayOrder: 4, status: 'active' },
  ]
};

async function seed() {
  try {
    await connectDB();
    const db = getDB();

    for (const [collectionName, data] of Object.entries(seedData)) {
      await db.collection(collectionName).deleteMany({});
      await db.collection(collectionName).insertMany(data);
      console.log(`Seeded ${collectionName} collection`);
    }

    console.log('Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await client.close();
  }
}

seed();
